###########################################################################
# MAKEFILE for AMD BC-250 Dream Drivers v3.0
# Simple makefile for WDK build
###########################################################################

!INCLUDE $(NTMAKEENV)\makefile.def
